import nbformat as nbf

nb = nbf.v4.new_notebook()

text_intro = """# KIVE Signal Analysis
Visualizing the separability of the 5 Expert Fraud signals generated by the KIVE microservices.
Signals shown:
- TAV (Temporal Anchoring Violations)
- SVP (Specificity Variance Profile) 
- FMD (Failure Memory Deficiency)
- MDC (Market Demand Correlation)
- TSI (Trajectory Smoothness Index)

**Expected Results:** Fraud profiles should consistently skew towards a score of 1.0 (highest fraud probability), while real experts skew towards 0.0.
"""

code_imports = """import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Apply professional styling
plt.style.use('dark_background')
sns.set_theme(style="darkgrid", rc={"axes.facecolor": "#111111", "figure.facecolor": "#111111", "axes.edgecolor": "#333333"})
"""

code_load = """df = pd.read_csv('../data/signal_distributions.csv')
print(f"Loaded {len(df)} profiles.")
df.head()
"""

code_plot = """signals = ['tav_score', 'svp_score', 'fmd_score', 'mdc_score', 'tsi_score']
titles = [
    'TAV (Temporal Anchoring Violations)', 
    'SVP (Specificity Variance Profile)', 
    'FMD (Failure Memory Deficiency)', 
    'MDC (Market Demand Correlation)', 
    'TSI (Trajectory Smoothness Index)'
]

fig, axes = plt.subplots(3, 2, figsize=(16, 18))
axes = axes.flatten()

for i, (sig, title) in enumerate(zip(signals, titles)):
    sns.kdeplot(
        data=df, 
        x=sig, 
        hue='label', 
        fill=True, 
        ax=axes[i], 
        palette={'REAL': '#00ffcc', 'FRAUD': '#ff3366'}, 
        alpha=0.6,
        linewidth=2
    )
    axes[i].set_title(title, color='white', pad=15, fontsize=14)
    axes[i].set_xlim(-0.1, 1.1)
    axes[i].set_xlabel("Fraud Score (0=Real, 1=Fraud)", color='gray')
    axes[i].set_ylabel("Density", color='gray')
    axes[i].tick_params(colors='gray')

axes[-1].remove() # Drop the 6th empty subplot
plt.tight_layout(pad=3.0)
plt.savefig('../docs/signal_distributions.png', dpi=300, bbox_inches='tight')
plt.show()
"""

code_correlation = """# View cross-signal correlations for fraud vs real
numeric_df = df[['label'] + signals]

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(18, 7))

sns.heatmap(numeric_df[numeric_df['label'] == 'REAL'].corr(numeric_only=True), 
            annot=True, cmap='viridis', vmin=-1, vmax=1, ax=ax1)
ax1.set_title("Cross-Signal Correlation (REAL EXPERTS)", color='white')

sns.heatmap(numeric_df[numeric_df['label'] == 'FRAUD'].corr(numeric_only=True), 
            annot=True, cmap='plasma', vmin=-1, vmax=1, ax=ax2)
ax2.set_title("Cross-Signal Correlation (FRAUD PROFILES)", color='white')

plt.tight_layout()
plt.show()
"""

nb['cells'] = [
    nbf.v4.new_markdown_cell(text_intro),
    nbf.v4.new_code_cell(code_imports),
    nbf.v4.new_code_cell(code_load),
    nbf.v4.new_code_cell(code_plot),
    nbf.v4.new_code_cell(code_correlation)
]

with open('notebooks/01_signal_analysis.ipynb', 'w') as f:
    nbf.write(nb, f)
print("Notebook generated successfully.")
