#!/usr/bin/env python3
"""Auto-copy artifacts to docs and update README with images."""
import json
import shutil
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent

# Images to copy from artifacts to docs
ARTIFACT_IMAGES = [
    ("artifacts/training/learning_curve.png", "docs/learning_curve.png"),
    ("artifacts/training/episode_traces.png", "docs/episode_traces.png"),
]

# Images generated by notebooks (already in docs via notebook export)
NOTEBOOK_IMAGES = [
    "docs/signal_distributions.png",
]

def copy_artifacts():
    """Copy training artifacts to docs folder"""
    print("Copying artifacts to docs...")
    for src, dst in ARTIFACT_IMAGES:
        src_path = PROJECT_ROOT / src
        dst_path = PROJECT_ROOT / dst
        if src_path.exists():
            shutil.copy2(src_path, dst_path)
            print(f"  [COPIED] {src} -> {dst}")
        else:
            print(f"  [MISSING] {src} not found")

def update_readme():
    """Update README with artifact images and metrics"""
    readme_path = PROJECT_ROOT / "README.md"
    
    # Read with UTF-8 encoding
    if readme_path.exists() and readme_path.stat().st_size > 0:
        readme = readme_path.read_text(encoding='utf-8')
    else:
        # Create basic README structure if empty
        readme = """# KIVE: Knowledge Integrity Verification Engine

RL-based expert fraud detection system using POMDP formulation with interactive probing.

## Results

Training results will appear here after running training.

## Quick Start

```bash
# Install dependencies
uv sync

# Generate synthetic data
uv run python data/synthetic_generator.py

# Train agent
uv run python services/orchestrator/train.py --mlflow

# Update docs with latest results
uv run python run.py update_docs

# Visualize MLflow runs
uv run python run.py visualize_mlflow
```

## Architecture

See `docs/architecture.md` for system design details.
"""
    
    # Load convergence report
    report_path = PROJECT_ROOT / "artifacts/training/convergence_report.json"
    if report_path.exists():
        report = json.loads(report_path.read_text(encoding='utf-8'))
        
        # Update results section with check/cross marks
        check = 'PASS' if report['fn_rate'] < 0.05 else 'FAIL'
        fp_check = 'PASS' if report['fp_rate'] < 0.08 else 'FAIL'
        conv_check = 'PASS' if report['converged'] else 'FAIL'
        
        results_section = f"""## Results

Latest training ({report['run_name']} - {report['n_episodes_actual']} episodes):
- FN rate: {report['fn_rate']:.3f} (target: <0.05) [{check}]
- FP rate: {report['fp_rate']:.3f} (target: <0.08) [{fp_check}]
- Mean probes: {report['mean_probes_per_episode']:.2f} (adaptive strategy)
- Probe variance: {report['probe_variance']:.2f} (context-dependent)
- Mean reward: {report['final_mean_reward']:.2f} (near-optimal)
- Converged: {str(report['converged']).lower()} [{conv_check}]

![Learning Curve](docs/learning_curve.png)
![Episode Traces](docs/episode_traces.png)

See `artifacts/training/convergence_report.json` for details."""
        
        # Replace results section
        if "## Results" in readme:
            start = readme.find("## Results")
            end = readme.find("\n## ", start + 1)
            if end == -1:
                end = len(readme)
            readme = readme[:start] + results_section + "\n\n" + readme[end:]
        
        # Write with UTF-8 encoding
        readme_path.write_text(readme, encoding='utf-8')
        print(f"\nUpdated README with latest metrics")

if __name__ == "__main__":
    copy_artifacts()
    update_readme()
    print("\n[SUCCESS] Docs updated successfully")
